- .gitignore
- .travis.yml
- README.md
- bin/test-all-exercises
- bin/test-exercise
- config.json
- exercises/leap/example/Leap.ceylon
- exercises/leap/source/leap/Leap.ceylon
- exercises/leap/source/leap/LeapTest.ceylon
- exercises/leap/source/leap/module.ceylon
You would think these are two unrelated things, but it seems to me that neither can stand on its own: I wouldn't want to add an exercise without assuring that it is in fact good, and making Travis test all exercises will have no effect unless there is some exercise to test.
So these together will get the track's inaugural exercise created and tested on Travis. Now that this work is done, hopefully less work to add future exercises.
> leap: add new exercise; travis: test each exercise

- config.json
- exercises/anagram/example/Anagram.ceylon
- exercises/anagram/source/anagram/Anagram.ceylon
- exercises/anagram/source/anagram/AnagramTest.ceylon
- exercises/anagram/source/anagram/module.ceylon
Reviewers: This PR has all commits from #8, because it needs the Travis work done there. After merging #8, there should only be one commit left (the one labeled "anagram"). It would be advantageous to review #8 before this one.
> anagram: Add new exercise

- exercises/anagram/source/anagram/AnagramTest.ceylon
- exercises/bracket-push/source/bracketpush/BracketsTest.ceylon
- exercises/leap/source/leap/LeapTest.ceylon
The [examples][blog] I looked at had `shared`, but I honestly do not see
why this has to be the case. Maybe it is necessary if the tests are
contained in a test class or something.
In either case, the tests still work without `shared`, so I'm removing
it. Principle of least privilege.
[blog]: https://ceylon-lang.org/blog/2016/02/22/ceylon-test-new-and-noteworthy/
> exercises: Remove shared from tests

- README.md
Student's only has ceylon.test, example's has whatever it needs.
This pattern has already been used in sieve (#16) and bracket-push (#13)
anyway, so it needs to be documented.
> README: distinguish between student's and example's module descriptors

- docs/TESTS.md
- exercises/TRACK_HINTS.md
If you follow the "Running the Tests" instructions verbatim, the tests will not run because the code hasn't been compiled yet. The proper way to run tests is `ceylon compile && ceylon test $(basename source/*)`.
> Document the need to compile before running tests

- exercises/anagram/source/anagram/AnagramTest.ceylon
- exercises/bracket-push/source/bracketpush/BracketsTest.ceylon
- exercises/hamming/source/hamming/HammingTest.ceylon
- exercises/largest-series-product/source/largestseriesproduct/SeriesTest.ceylon
- exercises/leap/source/leap/LeapTest.ceylon
- exercises/react/source/react/ReactorTest.ceylon
- exercises/sieve/source/sieve/SieveTest.ceylon
All canonical-data.json comply with https://github.com/exercism/x-common/issues/625.
They are versioned according to https://github.com/exercism/x-common/issues/673.
We can use this to tell whether our tests are out of date.
> Comment all tests with their x-common version

- exercises/hamming/source/hamming/HammingTest.ceylon
No additional action needs to be taken; we were already expecting an
error for the cases of unequal length (which is what 2.0.0 provides).
https://github.com/exercism/problem-specifications/pull/875
> hamming: declare compliance with problem-specifications 2.0.0

- exercises/rna-transcription/README.md
Original source seemed to mention a simple replacement of T with U
rather than the transcription being performed.
https://github.com/exercism/problem-specifications/issues/1078
https://github.com/exercism/problem-specifications/pull/1134
> rna-transcription: provide more accurate source info

- exercises/largest-series-product/example/Series.ceylon
- exercises/largest-series-product/source/largestseriesproduct/Series.ceylon
- exercises/largest-series-product/source/largestseriesproduct/SeriesTest.ceylon
The function being tested can error in multiple ways, so this is a great
time to see what programmatically-inspectable errors would look like.
> largest-series-product: Test for specific errors

- exercises/bracket-push/source/bracketpush/BracketsTest.ceylon
Guards against solutions immediately declaring the entire string matched
as soon as they find any one matched pair.
https://github.com/exercism/problem-specifications/pull/1219
> bracket-push 1.3.0: Add paired inside unpaired

- exercises/react/source/react/ReactorTest.ceylon
2.0.0: Combine expectCallbacks into setValue
https://github.com/exercism/problem-specifications/pull/1196
was already performed pre-emptively in
https://github.com/exercism/ceylon/pull/63
1.3.0: Multiple cells (the actual change here):
https://github.com/exercism/problem-specifications/pull/1197
> react 2.0.0: Test multiple cells

- exercises/rna-transcription/source/rnatranscription/RNATest.ceylon
1.3.0 added the empty case, which we already had
https://github.com/exercism/problem-specifications/issues/1264
https://github.com/exercism/problem-specifications/pull/1266
Empty case added to Ceylon track:
https://github.com/exercism/ceylon/pull/47#discussion_r134823457
> rna-transcription: no-op declare compliance with 1.3.0

- .travis.yml
Otherwise, Travis CI fails with:
Java not found, you must install Java in order to compile and run Ceylon programs
Go to http://www.java.com/getjava/ to download the latest version of Java
Unknown what changed.
It is known that sdkman version changed from 5.7.2+323 to 5.7.3+337
however nothing in 5.7.3 seems related, so not likely to be that.
A successful build:
https://travis-ci.org/exercism/ceylon/builds/434241647
A failed build:
https://travis-ci.org/exercism/ceylon/builds/437263366
> travis: Install java via sdkman

- .travis.yml
Well, 8.0.181-zulu isn't available anymore, but 8.0.192-zulu is! But it
does not make sense to have to update this file every time that changes.
> travis: Install any arbitrary 8.0 version

- config/maintainers.json
Otherwise, https://exercism.io/tracks/ceylon/maintainers would be empty,
and may dismay people into thinking there are no maintainers!!!
This makes my status and goal for the track clear.
> config/maintainers: show a bio for me on the website

- .travis.yml
- config.json
Want to prevent any invalid UUIDs from being entered.
Want to put this in configlet lint, but can't:
exercism/configlet#99
exercism/configlet#168
So it will go in individual tracks' .travis.yml for now.
It appears that the site will accept pretty much arbitrary strings as
UUIDs for now, but we want to make less work for ourselves when valid
UUIDs are required.
> travis: reject invalid UUIDs

- exercises/anagram/.meta/tests.toml
- exercises/hamming/.meta/tests.toml
- exercises/largest-series-product/.meta/tests.toml
- exercises/leap/.meta/tests.toml
- exercises/matching-brackets/.meta/tests.toml
- exercises/react/.meta/tests.toml
- exercises/rna-transcription/.meta/tests.toml
- exercises/sieve/.meta/tests.toml
We're in the process of re-opening the [Problem Specifications repo](https://github.com/exercism/problem-specifications), as discussed in [this issue](https://github.com/exercism/problem-specifications/issues/1674).
This PR adds `.meta/tests.toml` files for all exercises for which canonical data is defined in the Problem Specifications repo.
We'll now discuss _why_ we're making this change.
While most of the changes to the Problem Specifications repo are specific to that repo, there is one track-specific change:
> If a track implements an exercise for which test data exists, the exercise _must_ contain a `.meta/tests.toml` file.
The goal of the `tests.toml` file is to keep track of which tests are implemented by the exercise.
Tests in this file are identified by their UUID and each test …
> Bringing your track in line with the latest changes to Problem Specifications

- exercises/anagram/source/anagram/AnagramTest.ceylon
- exercises/hamming/source/hamming/HammingTest.ceylon
- exercises/largest-series-product/source/largestseriesproduct/SeriesTest.ceylon
- exercises/leap/source/leap/LeapTest.ceylon
- exercises/matching-brackets/source/matchingbrackets/BracketsTest.ceylon
- exercises/react/source/react/ReactorTest.ceylon
- exercises/rna-transcription/source/rnatranscription/RNATest.ceylon
- exercises/sieve/source/sieve/SieveTest.ceylon
since we're in the new world of .meta/tests.toml now.
However, I had to leave in the reference where the Ceylon track keeps
some tests that are no longer in the canonical data.
> remove most references to problem-specifications versions

- config/maintainers.json
This resignation is effective for the Ceylon track only. Other tracks
will be evaluated on a case-by-case basis.
The primary reason is that I've moved on from the language.
I haven't even had it installed for the past few years and have pretty
much solely relied on CI to see whether things still compile.
The secondary reason is it's too lonely being a sole maintainer.
(But even if another maintainer for this language were to become active,
the primary reason would still remain, so that will not cause me to
reconsider this resignation)
The track was a useful way to test tooling since it was a small track
with few exercises, but I think that if the need arises to test tooling
then I would be better served finding a different small track to use.
> maintainers: my resignation as a Ceylon track maintainer

- exercises/practice/anagram/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/matching-brackets/.meta/config.json
- exercises/practice/react/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/sieve/.meta/config.json
Each Concept and Practice Exercise will have to define a _blurb_, which is a short description of the exercise.
The blurb will be displayed on a track's exercises page and on exercise tooltips. For example:
Blurbs must be limited to 350 chars and will be truncated in some views.
For Practice Exercises that are based on an exercise defined in the problem-specification repo, the blurb must match the contents of the problem-specifications exercises, which is defined in its `metadata.yml` file. In this PR, we'll do an initial syncing of the blurb. The new [configlet](https://github.com/exercism/configlet) version will add support for doing this syncing automatically.
If the Practice Exercise was _not_ based on a problems-specifications exercise, we've used the blurb from its …
> 🤖 Add blurb to .meta/config.json files

- exercises/practice/anagram/.meta/tests.toml
- exercises/practice/hamming/.meta/tests.toml
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/leap/.meta/tests.toml
- exercises/practice/matching-brackets/.meta/tests.toml
- exercises/practice/react/.meta/tests.toml
- exercises/practice/rna-transcription/.meta/tests.toml
- exercises/practice/sieve/.meta/tests.toml
Track maintainers found that they wanted to add comments to the tests.toml file to e.g. indicate _why_ a test was not included.
Unfortunately, running configlet sync would re-generate the entire file so any manually added comments were lost.
In this PR we're updating the format of tests.toml files to support adding comments.
We do this by creating a separate table for each test case which has `description` and `include` fields.
Tracks are then free to add additional fields, like a `comment` field, but also any other fields they feel might be useful to them.
configlet has _not_ yet been updated to support this new format, but we hope to do this soon. Sorry for the inconvenience.
For more information, see this discussion: https://github.com/exercism/configlet/issues/186
The PR expects the …
> 🤖 Update tests.toml files to latest spec

- exercises/practice/anagram/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/matching-brackets/.meta/config.json
- exercises/practice/react/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/sieve/.meta/config.json
_If you got tagged in this PR, it is because you are being credited for work you've done in the past on Exercism here, and we want to ensure you don't miss out on the recognition you deserve 🙂_
---
With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercises' `.meta/config.json` files (see [the docs](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson)).
Concept Exercises, which are all new, already contain authors and contributors. Practice Exercises though are missing this information. In this PR, we attempt to populate the authors and contributors of Practice Exercises based on their commit history.
These are the things you, the maintainers, should do:
**For clarity, authors should …
> 🤖 Add authors and contributors to Practice Exercises

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/source/largestseriesproduct/SeriesTest.ceylon
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications
